### PR TITLE
classicons: Fake the unit if the player is in a vehicle

### LINKED ISSUE #297: ClassIcons: error when starting quest "Huln's War - The Arrival"
In the "Huln's War - The Arrival" quest you speak to an NPC which then transfers you to Azshara and force you into a vehicle state.

This causes the following error when playing on a Shadow Priest:
```
Message: ...e\AddOns\ElvUI\Libraries\oUF\elements\classicons.lua line 109:
   attempt to index field '?' (a nil value)
Debug:
   ...e\AddOns\ElvUI\Libraries\oUF\elements\classicons.lua:109:
      ...e\AddOns\ElvUI\Libraries\oUF\elements\classicons.lua:73
   (tail call): ?
   ...e\AddOns\ElvUI\Libraries\oUF\elements\classicons.lua:170:
      ...e\AddOns\ElvUI\Libraries\oUF\elements\classicons.lua:147
   (tail call): ?
   ElvUI\Libraries\oUF\ouf.lua:174: UpdateAllElements()
   ...ace\AddOns\ElvUI\Modules\unitframes\units\player.lua:193:
      ...ace\AddOns\ElvUI\Modules\unitframes\units\player.lua:80
   [C]: ?()
   ...rface\AddOns\ElvUI\Modules\unitframes\unitframes.lua:905: Update()
   ...rface\AddOns\ElvUI\Modules\unitframes\unitframes.lua:454: Update_AllFrames()
   ...rface\AddOns\ElvUI\Modules\unitframes\unitframes.lua:1125: ?()
   ...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: Fire()
   ...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
```

I added some debug prints to try to understand what is happening, and this is the result:
```
VisibilityPath: PLAYER_ENTERING_WORLD player
Path: ClassPowerEnable vehicle COMBO_POINTS
Update event, unit, powerType: ClassPowerEnable vehicle COMBO_POINTS
Update cur, max: 0 5
VisibilityPath: nil player
Path: nil player nil
Update event, unit, powerType: nil player nil
Update cur, max: 0 100
VisibilityPath: RefreshUnit vehicle
Path: RefreshUnit vehicle COMBO_POINTS
Update event, unit, powerType: RefreshUnit vehicle COMBO_POINTS
Update cur, max: 0 5
```

The important part is this:
```
VisibilityPath: nil player
Path: nil player nil
Update event, unit, powerType: nil player nil
Update cur, max: 0 100
```

For some reason an Update is triggered with nil values for event and powerType while unit is "player".

We may need to check for this scenario at the top of the Update function and prevent it from going further. Another solution could be to simply check if "element[i]" exists before trying to show or hide it in this block of code:
```
for i = 1, max do
	if(i <= cur) then
		element[i]:Show()
	else
		element[i]:Hide()
	end
end
```

### PR DESCRIPTION
**Pull request by p3lim**
Should fix #297.

### CODE REVIEW

**Comment by Rainrider** [comment]
We were not getting vehicle events on the player frame since 8eb10006ac9232e429312ee49a10a4b544f9dc3f.
One solution would have been to use 'pet' to get vehicle data, but events seems to fire for the 'vehicle' unit faster.
I tested this and it is working as intended now. The only minor issue is when a /reload is done while in a vehicle with present combo points - none will be displayed until the next UNIT_POWER_FREQUENT with 'vehicle' as unit and 'COMBO_POINTS' as powerType. This is due to `GetComboPoints` returning 0 at PLAYER_ENTERING_WORLD.

**Comment by ls-** [comment]
I think I should start nagging TheDanW to fix `UnitPower` for vehicles 😂

**Comment by ls-** [comment]
K, tested it w/ ElvUI and my UI. Everything works the way @Rainrider described.

**Comment by ls-** [comment]
> TheDanW  ls-: looks like its already being tracked internally - wouldn't expect a fix any time soon, turns out to be more complicated than it appears

💩

**Comment by Rainrider** [comment]
I've read this answer like a million times already :)

**Pull request merged**
