### PR TITLE
element: Add power gain/loss indicator [WIP]

### PR DESCRIPTION
**Pull request by ls-**
~~This one addresses #308.~~

Scrapped in favour of layout-based solution.

```Lua
local power = CreateFrame("StatusBar", nil, frame)
power:SetPoint("CENTER", "UIParent", "CENTER", -256, 256)
power:SetSize(238, 24)
power:SetStatusBarTexture("Interface\\BUTTONS\\WHITE8X8")
power.colorPower = true
power.frequentUpdates = true
frame.Power = power

local bg = power:CreateTexture(nil, "BACKGROUND")
bg:SetAllPoints()
bg:SetColorTexture(1, 1, 1)
bg.multiplier = 0.2
power.bg = bg

local diffThreshold = 0.1

power.PostUpdate = function(self, _, cur, max)
	local prev = bar.prev or 0
	local diff = cur - prev

	if math.abs(diff) / max < diffThreshold then
		diff = 0
	end

	if diff > 0 then
		if self.Gain:GetAlpha() == 0 then
			local offset = self:GetWidth() * (1 - prev / max)

			self.Gain:SetAlpha(1)
			self.Gain:SetPoint("TOPLEFT", self, "TOPRIGHT", -offset, 0)
			self.Gain:SetPoint("BOTTOMLEFT", self, "BOTTOMRIGHT", -offset, 0)
			self.Gain.FadeOut:Play()
		end
	elseif diff < 0 then
		self.Gain.FadeOut:Stop()
		self.Gain:SetAlpha(0)

		if self.Loss:GetAlpha() == 0 then
			local offset = self:GetWidth() * (1 - prev / max)

			self.Loss:SetAlpha(1)
			self.Loss:SetPoint("TOPRIGHT", self, "TOPRIGHT", -offset, 0)
			self.Loss:SetPoint("BOTTOMRIGHT", self, "BOTTOMRIGHT", -offset, 0)
			self.Loss.FadeOut:Play()
		end
	end

	bar.prev = cur
end

local gainTexture = power:CreateTexture(nil, "OVERLAY")
gainTexture:SetPoint("TOPRIGHT", power:GetStatusBarTexture(), "TOPRIGHT", 0, 0)
gainTexture:SetPoint("BOTTOMRIGHT", power:GetStatusBarTexture(), "BOTTOMRIGHT", 0, 0)
gainTexture:SetColorTexture(0, 1, 0)
gainTexture:SetAlpha(0)
power.Gain = gainTexture

local lossTexture = power:CreateTexture(nil, "BACKGROUND")
lossTexture:SetPoint("TOPLEFT", power:GetStatusBarTexture(), "TOPRIGHT", 0, 0)
lossTexture:SetPoint("BOTTOMLEFT", power:GetStatusBarTexture(), "BOTTOMRIGHT", 0, 0)
lossTexture:SetColorTexture(1, 0, 0)
lossTexture:SetAlpha(0)
power.Loss = lossTexture

local ag = gainTexture:CreateAnimationGroup()
ag:SetToFinalAlpha(true)
gainTexture.FadeOut = ag

local anim1 = ag:CreateAnimation("Alpha")
anim1:SetFromAlpha(1)
anim1:SetToAlpha(0)
anim1:SetStartDelay(0.6)
anim1:SetDuration(0.2)

ag = lossTexture:CreateAnimationGroup()
ag:SetToFinalAlpha(true)
lossTexture.FadeOut = ag

anim1 = ag:CreateAnimation("Alpha")
anim1:SetFromAlpha(1)
anim1:SetToAlpha(0)
anim1:SetStartDelay(0.6)
anim1:SetDuration(0.2)
```

### CODE REVIEW

**Comment by ls-** [comment]
Alternatively I could re-implement it as a set of **two** status bars, one for gain, another one for loss.
This way they could be attached to `frame.Power:GetStatusBarTexture()`, however, it'd look weirdly/wobbly if layout dev used some kind of bar "smoothing", or if character had some kind of fast regenerating power, e.g. rogue's energy.

**Comment by ls-** [comment]
Decided to split it into two sub-widgets. This way devs will be able to do fancier stuff 😁

Added few more returns, they'll help people to calculate coordinates more accurately, `:GetPoint()` returns were quite unreliable, when bar "smoothing" is applied.

Also updated example code to reflect changes.

**Comment by Rainrider** [comment]
Sorry for restraining from commenting on this one, I simply can't see what this is good for. Does it provide any information I would base my spells priority on?

**Comment by p3lim** [comment]
Blizzard calls it "Feedback", it's defined in [FrameXML/BuilderSpenderFrame.lua](https://github.com/tekkub/wow-ui-source/blob/live/FrameXML/BuilderSpenderFrame.lua), where there's also a "FullResourcePull" widget (typically used for energy-based classes/specs).

**Comment by ls-** [comment]
@Rainrider, it's as "useful" as `PowerPrediction`, it's pretty much cosmetic, and so is power prediction, but a) it allows to mimic default power bars behaviour w/o using `OnUpdate`s, etc; b) what @p3lim said; c) why not? O_o

And we're here to discuss its viability, there's no problem w/ not liking something, and saying **no** to it. If we decide that it's not suitable for oUF core itself, it can always be released as a plugin 😃

**Comment by ls-** [comment]
TBH, I agree w/ @Rainrider, at this point I'm not even sure that these should be status bars, or even an element. I was against making one in the first place, lol, but I changed my mind that time, and I'm changing it again now 😒

We could simply add "old" power value to power's `PostUpdate`, cuz a lot of maths voodoo could be avoided by permanently attaching one side of the texture to `power:GetStatusBarTexture()`, and another side would be attached in `PostUpdate`, and old value would be used to calculate coords.

**Comment by ls-** [comment]
So, I added prev/old value to my power's PostUpdate, and here's the result 😁 


```Lua
local power = _G.CreateFrame("StatusBar", nil, frame)
power:SetPoint("CENTER", "UIParent", "CENTER", -256, 256)
power:SetStatusBarTexture("Interface\\BUTTONS\\WHITE8X8")power:SetSize(238, 24)
power.colorPower = true
power.frequentUpdates = true
frame.Power = power

local bg = power:CreateTexture(nil, "BACKGROUND")
bg:SetAllPoints()
bg:SetColorTexture(1, 1, 1)
bg.multiplier = 0.2
power.bg = bg

local diffThreshold = 0.1

power.PostUpdate = function(self, _, cur, max, _, _, _, prev)
	local diff = cur - prev

	if math.abs(diff) / max < diffThreshold then
		diff = 0
	end

	if diff > 0 then
		if self.Gain:GetAlpha() == 0 then
			local offset = self:GetWidth() * (1 - prev / max)

			self.Gain:SetAlpha(1)
			self.Gain:SetPoint("TOPLEFT", self, "TOPRIGHT", -offset, 0)
			self.Gain:SetPoint("BOTTOMLEFT", self, "BOTTOMRIGHT", -offset, 0)
			self.Gain.FadeOut:Play()
		end
	elseif diff < 0 then
		self.Gain.FadeOut:Stop()
		self.Gain:SetAlpha(0)

		if self.Loss:GetAlpha() == 0 then
			local offset = self:GetWidth() * (1 - prev / max)

			self.Loss:SetAlpha(1)
			self.Loss:SetPoint("TOPRIGHT", self, "TOPRIGHT", -offset, 0)
			self.Loss:SetPoint("BOTTOMRIGHT", self, "BOTTOMRIGHT", -offset, 0)
			self.Loss.FadeOut:Play()
		end
	end
end

local gainTexture = power:CreateTexture(nil, "OVERLAY")
gainTexture:SetPoint("TOPRIGHT", power:GetStatusBarTexture(), "TOPRIGHT", 0, 0)
gainTexture:SetPoint("BOTTOMRIGHT", power:GetStatusBarTexture(), "BOTTOMRIGHT", 0, 0)
gainTexture:SetColorTexture(0, 1, 0)
gainTexture:SetAlpha(0)
power.Gain = gainTexture

local lossTexture = power:CreateTexture(nil, "BACKGROUND")
lossTexture:SetPoint("TOPLEFT", power:GetStatusBarTexture(), "TOPRIGHT", 0, 0)
lossTexture:SetPoint("BOTTOMLEFT", power:GetStatusBarTexture(), "BOTTOMRIGHT", 0, 0)
lossTexture:SetColorTexture(1, 0, 0)
lossTexture:SetAlpha(0)
power.Loss = lossTexture

local ag = gainTexture:CreateAnimationGroup()
ag:SetToFinalAlpha(true)
gainTexture.FadeOut = ag

local anim1 = ag:CreateAnimation("Alpha")
anim1:SetOrder(1)
anim1:SetFromAlpha(1)
anim1:SetToAlpha(0)
anim1:SetStartDelay(0.6)
anim1:SetDuration(0.2)

ag = lossTexture:CreateAnimationGroup()
ag:SetToFinalAlpha(true)
lossTexture.FadeOut = ag

anim1 = ag:CreateAnimation("Alpha")
anim1:SetOrder(1)
anim1:SetFromAlpha(1)
anim1:SetToAlpha(0)
anim1:SetStartDelay(0.6)
anim1:SetDuration(0.2)
```

So yeah, it can be done w/o adding new element, we just need to tweak existing one.
I'm not going to open new PR, it's a part of this one, it's marked [WIP] for a reason.

But here's a question:
```Lua
if(power.PostUpdate) then
	return power:PostUpdate(unit, cur, max, min, ptoken, ptype, prev)
end
```
OR
```Lua
if(power.PostUpdate) then
	return power:PostUpdate(unit, cur, max, min, prev, ptoken, ptype)
end
```

First one is backward compatible, second one makes more sense, sorta...

**Comment by haste** [comment]
Can't the layout author just fetch the value in the PreUpdate?

Also, I believe the next release needs a major bump, so a logical argument order should trump backwards compat.

**Comment by ls-** [comment]
@haste, nope, cuz A) obviously `UnitPower` will return current value, B) if some kind of bar animation is used, e.g. oUF_Smooth, `statusbar:GetValue()` returns are unreliable.

**Comment by p3lim** [comment]
> if some kind of bar animation/smoothing is used, e.g. oUF_Smooth, statusbar:GetValue() or statusbar:GetStatusBarTexture:GetPoint() returns may be quite unreliable.

Their problem, not ours. If we really want to be nice we could store the value in a key like 'old' or something.

> IMHO, AdditionalPower should receive same treatment

Yes.

**Comment by ls-** [comment]
> Their problem, not ours. If we really want to be nice we could store the value in a key like 'old' or something.

That's what I'm suggesting.

```diff
diff --git a/elements/power.lua b/elements/power.lua
index 5389eb9..bc453e4 100644
--- a/elements/power.lua
+++ b/elements/power.lua
@@ -155,6 +155,7 @@ local Update = function(self, event, unit)
 	local cur, max = UnitPower(unit, displayType), UnitPowerMax(unit, displayType)
 	local disconnected = not UnitIsConnected(unit)
 	local tapped = not UnitPlayerControlled(unit) and UnitIsTapDenied(unit)
+	local prev = power.prev or 0
 	power:SetMinMaxValues(min or 0, max)
 
 	if(disconnected) then
@@ -165,6 +166,7 @@ local Update = function(self, event, unit)
 
 	power.disconnected = disconnected
 	power.tapped = tapped
+	power.prev = cur
 
 	local ptype, ptoken, altR, altG, altB = UnitPowerType(unit)
 	local r, g, b, t
@@ -233,7 +235,7 @@ local Update = function(self, event, unit)
 	end
 
 	if(power.PostUpdate) then
-		return power:PostUpdate(unit, cur, max, min, ptoken, ptype)
+		return power:PostUpdate(unit, cur, max, min, ptoken, ptype, prev)
 	end
 end
```

**Comment by p3lim** [comment]
@ls- That wouldn't work, you're replacing prev with cur every update, it's the same as cur.

**Comment by ls-** [comment]
@p3lim, read the diff thoroughly 😁

I cache previous power.prev value and then pass it to `PostUpdate`.

**Comment by p3lim** [comment]
Ah right.

**Comment by ls-** [comment]
Hm, true... We don't need to change anything then 👍

**Pull request closed without merging**
