### PR TITLE
Replace Travis with GitHub Actions

### PR DESCRIPTION
**Pull request by p3lim**

### CODE REVIEW

**Comment by Rainrider** [comment]
Is this packaging all tags?

**Comment by p3lim** [comment]
Yup

**Comment by Rainrider** [comment]
@p3lim please take a look at https://github.com/oUF-wow/oUF/pull/532/checks?check_run_id=968627384#step:6:79
It seems the version was stripped from the file name for w/e reason.

**Review by Rainrider — APPROVED** [review]
Just added groups (💄) and bumped to the latest commit of the packager.
:shipit: @p3lim

**Pull request merged**
