### PR TITLE
Fix additional power color

### PR DESCRIPTION
**Pull request by siweia**

### CODE REVIEW

**Comment by ls-** [comment]
Sup!
Alt power bar fix looks weird, alt power colour can be accessed via both index and name because of [this](https://github.com/oUF-wow/oUF/blob/master/colors.lua#L121-L122).
If you use custom alt power colour, how do you override it? Could you post dumps of your unit frame's colour table?
```
/dump UFNAME.colors.power[Enum.PowerType.Alternate]
/dump UFNAME.colors.power.ALTERNATE
```

**Comment by siweia** [comment]
It is within additional power, not alt power.

**Comment by ls-** [comment]
I'm fooking blind, mate 😁 🔫 But the same questions still stand. Post your dumps
```
/dump UFNAME.colors.power[ADDITIONAL_POWER_BAR_NAME]
/dump UFNAME.colors.power[ADDITIONAL_POWER_BAR_INDEX]
```
Should be something like this:
image

**Comment by siweia** [comment]
I change the MANA color in my own layout.
`oUF.colors.power.MANA = {0, .4, 1}`

Here is the dump:

**Comment by ls-** [comment]
When you override any colour you have to override at its index AND its name. It's also brought up in https://github.com/oUF-wow/oUF/issues/546 recently. I also explained why you have to do it that way.

**Comment by siweia** [comment]
Ok, thanks.

**Comment by ls-** [comment]
You're welcome ❤

**Pull request closed without merging**
