### PR TITLE
power: replace deprecated UnitAlternatePowerInfo

### PR DESCRIPTION
**Pull request by myzb**

### CODE REVIEW

**Comment by myzb** [comment]
I dunno how you handle dev for the shadowlands branch. I ran into this one while updating my layout and felt like give something back to the community :)

**Comment by p3lim** [comment]
I think the wrapper function can just be removed, other than that it looks good.

**Review by p3lim — APPROVED** [review]

**Comment by Rainrider** [comment]
This has already been fixed [here](https://github.com/oUF-wow/oUF/pull/490/commits/dc5b3c7bee3888f7e21bd9a0856c80b5507f8b29). We should be able to merge it pretty soon.

**Comment by p3lim** [comment]
Ah, must have missed that one.

**Pull request closed without merging**
