### PR TITLE
changelog: Add links to issues mentioned in commit messages

### PR DESCRIPTION
**Pull request by p3lim**

### CODE REVIEW

**Comment by haste** [comment]
This should just match for `#\d+` and use that for GitHub issue linking. Seems odd to only allow `\(#\d+\)$`.

**Comment by Rainrider** [comment]
@haste There might be other numbers in the commit message. Or do you mean something else?

**Comment by haste** [comment]
Other numbers in the commit message in the format of `#<digits>`?

**Comment by Rainrider** [comment]
Ah, yes, the `#`

**Pull request merged**
