### PR TITLE
Adding a spawn function for nameplates (they must not be secure)

### PR DESCRIPTION
**Pull request by zorker**
More on that http://www.wowinterface.com/forums/showthread.php?t=54584

### CODE REVIEW

**Comment by p3lim** [comment]
If we're going to support nameplates we're also gonna have the system itself disable the default ones.

Something like this:
```Diff
diff --git a/blizzard.lua b/blizzard.lua
index d85118f..a26f60c 100644
--- a/blizzard.lua
+++ b/blizzard.lua
@@ -98,5 +98,7 @@ function oUF:DisableBlizzard(unit)
 		-- Blizzard_ArenaUI should not be loaded
 		Arena_LoadUI = function() end
 		SetCVar('showArenaEnemyFrames', '0', 'SHOW_ARENA_ENEMY_FRAMES_TEXT')
+	elseif(unit:match'(nameplate)%d?$' == 'nameplate') then
+		HandleFrame(NamePlateDriverFrame)
 	end
 end
diff --git a/ouf.lua b/ouf.lua
index 46c90dd..b4522d3 100644
--- a/ouf.lua
+++ b/ouf.lua
@@ -538,14 +538,19 @@ do
 	end
 end
 
-function oUF:Spawn(unit, overrideName)
+function oUF:Spawn(unit, overrideName, nameplateParent)
 	argcheck(unit, 2, 'string')
 	if(not style) then return error("Unable to create frame. No styles have been registered.") end
 
 	unit = unit:lower()
 
-	local name = overrideName or generateName(unit)
-	local object = CreateFrame("Button", name, oUF_PetBattleFrameHider, "SecureUnitButtonTemplate")
+	local name, object = overrideName or generateName(unit)
+	if(nameplateParent) then
+		object = CreateFrame("Button", name, nameplateParent)
+	else
+		object = CreateFrame("Button", name, oUF_PetBattleFrameHider, "SecureUnitButtonTemplate")
+	end
+
 	Private.UpdateUnits(object, unit)
 
 	self:DisableBlizzard(unit)
```

**Comment by p3lim** [comment]
TBH, it should rather work like the header system, let oUF control all nitty gritty so that the layout can only worry about the layout (as oUF intends).
That means no handling of the nameplate spawning events in the layout.

**Comment by Sticklord** [comment]
This could still be a temporary thing, so you can use oUF layouts until full support is added.

**Comment by zorker** [comment]
Sure thing. The above is only needed to get it working at all. Here is my spawn code that disables the default Blizzard frames and does the event management to show/hide all the nameplates.

What is not included is the style function and the two lines needed to set and activate a style. I have a seperate style for nameplates.

local W = CreateFrame("Frame") --worker
    local UFM = {} --unit frame mixin
    local C_NamePlate = C_NamePlate

    -----------------------------
    -- Hide Blizzard
    -----------------------------

    function W:UpdateNamePlateOptions(...)
      --print("UpdateNamePlateOptions",...)
    end

    --disable blizzard nameplates
    NamePlateDriverFrame:UnregisterAllEvents()
    NamePlateDriverFrame:Hide()
    NamePlateDriverFrame.UpdateNamePlateOptions = W.UpdateNamePlateOptions

    -----------------------------
    -- Worker
    -----------------------------

    function W:NAME_PLATE_UNIT_ADDED(unit)
      local nameplate = C_NamePlate.GetNamePlateForUnit(unit)
      if not nameplate.unitFrame then
        local unitFrame = oUF:SpawnNamePlate(unit, A..nameplate:GetName(),nameplate)
        unitFrame:EnableMouse(false)
        nameplate.unitFrame = unitFrame
        Mixin(unitFrame, UFM)
      end
      nameplate.unitFrame:UnitAdded(nameplate,unit)
    end

    function W:NAME_PLATE_UNIT_REMOVED(unit)
      local nameplate = C_NamePlate.GetNamePlateForUnit(unit)
      nameplate.unitFrame:UnitRemoved(nameplate,unit)
    end

    function W:PLAYER_TARGET_CHANGED()
      local nameplate = C_NamePlate.GetNamePlateForUnit("target")
      if nameplate then
        nameplate.unitFrame:PlayerTargetChanged(nameplate,"target")
      end
    end

    function W:OnEvent(event,...)
      self[event](event,...)
    end

    W:SetScript("OnEvent", W.OnEvent)

    W:RegisterEvent("NAME_PLATE_UNIT_ADDED")
    W:RegisterEvent("NAME_PLATE_UNIT_REMOVED")
    W:RegisterEvent("PLAYER_TARGET_CHANGED")

    -----------------------------
    -- Unit Frame Mixin
    -----------------------------

    function UFM:UnitAdded(nameplate,unit)
      self:SetAttribute("unit", unit)
      self:UpdateAllElements("NAME_PLATE_UNIT_ADDED")
    end

    function UFM:PlayerTargetChanged(nameplate,unit)
      self:UpdateAllElements("PLAYER_TARGET_CHANGED")
    end

    function UFM:UnitRemoved(nameplate,unit)
      self:SetAttribute("unit", nil)
      self:UpdateAllElements("NAME_PLATE_UNIT_REMOVED")
    end

**Comment by zorker** [comment]
Added auras. No issues occured at all. It is fucking amazing!

http://i.imgur.com/vmjAGET.jpg

**Comment by zorker** [comment]
I optimized the nameplate code even more and capsuled all the nameplate stuff inside a spawn function for all nameplates. Here is my full solution:

```lua
function oUF:SpawnNamePlate(unit, overrideName, nameplate)
  argcheck(unit, 2, 'string')
  if(not style) then return error("Unable to create frame. No styles have been registered.") end
  unit = unit:lower()
  local name = overrideName or generateName(unit)
  local object = CreateFrame("Button", name, nameplate)
  Private.UpdateUnits(object, unit)
  walkObject(object, unit)
  object:SetAttribute("unit", unit)
  return object
end

--oUF:SpawnNamePlates
function oUF:SpawnNamePlates(styleName,namePrefix,nameplateOptionsFunc)
  local function UpdateNamePlateOptions(...)
    --print("UpdateNamePlateOptions",...)
  end
  --disable blizzard nameplates
  NamePlateDriverFrame:UnregisterAllEvents()
  NamePlateDriverFrame:Hide()
  NamePlateDriverFrame.UpdateNamePlateOptions = nameplateOptionsFunc or UpdateNamePlateOptions
  --nameplate event handler
  local NPEH = CreateFrame("Frame")
  local C_NamePlate = C_NamePlate
  NPEH.activeStyle = styleName
  --NPEH:NAME_PLATE_UNIT_ADDED
  function NPEH:NAME_PLATE_UNIT_ADDED(event,unit)
    local nameplate = C_NamePlate.GetNamePlateForUnit(unit)
    if not nameplate then return end
    if not nameplate.unitFrame then
      --spawn nameplate unitframe on nameplate base
      oUF:SetActiveStyle(self.activeStyle)
      nameplate.unitFrame = oUF:SpawnNamePlate(unit, namePrefix..nameplate:GetName(),nameplate)
      nameplate.unitFrame:EnableMouse(false) --do I need this?!
    end
    nameplate.unitFrame:SetAttribute("unit", unit)
    nameplate.unitFrame:UpdateAllElements("NAME_PLATE_UNIT_ADDED")
  end
  --NPEH:NAME_PLATE_UNIT_REMOVED
  function NPEH:NAME_PLATE_UNIT_REMOVED(event,unit)
    local nameplate = C_NamePlate.GetNamePlateForUnit(unit)
    if not nameplate then return end
    nameplate.unitFrame:SetAttribute("unit", nil)
    nameplate.unitFrame:UpdateAllElements("NAME_PLATE_UNIT_REMOVED")
  end
  --NPEH:PLAYER_TARGET_CHANGED
  function NPEH:PLAYER_TARGET_CHANGED(event)
    local nameplate = C_NamePlate.GetNamePlateForUnit("target")
    if not nameplate then return end
    nameplate.unitFrame:UpdateAllElements("PLAYER_TARGET_CHANGED")
  end
  --NPEH:OnEvent
  function NPEH:OnEvent(event,...)
    self[event](self,event,...)
  end
  NPEH:SetScript("OnEvent", NPEH.OnEvent)
  NPEH:RegisterEvent("NAME_PLATE_UNIT_ADDED")
  NPEH:RegisterEvent("NAME_PLATE_UNIT_REMOVED")
  NPEH:RegisterEvent("PLAYER_TARGET_CHANGED")
end
```

**Comment by p3lim** [comment]
Keep on playing around with it, very valuable information.

**Comment by zorker** [comment]
I just recognized that the "player" nameplate works out of the box aswell. I had it disabled all the time. But as soon as I enabled it it popped up perfectly styled. >_<

http://imgur.com/a/lEMA7

But...it would be nice if it would be possible to give it a different style. This should be doable by passing a second style. The frame identification can be done by UnitIsUnit("player",unit) on the nameplate generation. This would only be possible though is the player nameplate does not shuffle like the other nameplates do.

**Comment by zorker** [comment]
I finished all my tests. Here is the final integration that I'm currently running with:

Changes to oUF/oUF.lua

```lua
function oUF:Spawn(unit, overrideName, nameplate)
	argcheck(unit, 2, 'string')
	if(not style) then return error("Unable to create frame. No styles have been registered.") end
	unit = unit:lower()
	local name = overrideName or generateName(unit)
	local object
	if nameplate then
		object = CreateFrame("Button", name, nameplate)
	else
		object = CreateFrame("Button", name, oUF_PetBattleFrameHider, "SecureUnitButtonTemplate")
	end
	Private.UpdateUnits(object, unit)
	if not nameplate then
		self:DisableBlizzard(unit)
	end
	walkObject(object, unit)
	object:SetAttribute("unit", unit)
	if not nameplate then
		RegisterUnitWatch(object)
	end
	return object
end

--oUF:SpawnNamePlates
function oUF:SpawnNamePlates(styleName,namePrefix,nameplateCallback)
	local function UpdateNamePlateOptions(...)
		if nameplateCallback then
			nameplateCallback("UpdateNamePlateOptions",...)
		end
	end
	--disable blizzard nameplates
	NamePlateDriverFrame:UnregisterAllEvents()
	NamePlateDriverFrame:Hide()
	NamePlateDriverFrame.UpdateNamePlateOptions = UpdateNamePlateOptions
	--nameplate event handler
	local NPEH = CreateFrame("Frame")
	local C_NamePlate = C_NamePlate
	NPEH.activeStyle = styleName
	--NPEH:NAME_PLATE_UNIT_ADDED
	function NPEH:NAME_PLATE_UNIT_ADDED(event,unit)
		local nameplate = C_NamePlate.GetNamePlateForUnit(unit)
		if not nameplate then return end
		if not nameplate.unitFrame then
			--spawn nameplate unitframe on nameplate base
			oUF:SetActiveStyle(self.activeStyle)
			nameplate.unitFrame = oUF:Spawn(unit, namePrefix..nameplate:GetName(),nameplate)
			nameplate.unitFrame:EnableMouse(false)
		end
		nameplate.unitFrame:SetAttribute("unit", unit)
		nameplate.unitFrame:UpdateAllElements(event)
		if nameplateCallback then
			nameplateCallback(event,nameplate,unit)
		end
	end
	--NPEH:NAME_PLATE_UNIT_REMOVED
	function NPEH:NAME_PLATE_UNIT_REMOVED(event,unit)
		local nameplate = C_NamePlate.GetNamePlateForUnit(unit)
		if not nameplate then return end
		nameplate.unitFrame:SetAttribute("unit", nil)
		nameplate.unitFrame:UpdateAllElements(event)
		if nameplateCallback then
			nameplateCallback(event,nameplate,unit)
		end
	end
	--NPEH:PLAYER_TARGET_CHANGED
	function NPEH:PLAYER_TARGET_CHANGED(event)
		local nameplate = C_NamePlate.GetNamePlateForUnit("target")
		if not nameplate then return end
		nameplate.unitFrame:UpdateAllElements(event)
		if nameplateCallback then
			nameplateCallback(event,nameplate)
		end
	end
	--NPEH:OnEvent
	function NPEH:OnEvent(event,...)
		self[event](self,event,...)
	end
	NPEH:SetScript("OnEvent", NPEH.OnEvent)
	NPEH:RegisterEvent("NAME_PLATE_UNIT_ADDED")
	NPEH:RegisterEvent("NAME_PLATE_UNIT_REMOVED")
	NPEH:RegisterEvent("PLAYER_TARGET_CHANGED")
end

How to spawn all nameplates:

```lua
  oUF:RegisterStyle(styleName, styleFunc) --styleName: String, styleFunc: Function
  oUF:SpawnNamePlates(styleName, namePrefix, callbackFunc) --styleName: String, namePrefix: String, callbackFunc: Function
```

The callback fires on any registered nameplate event and is an optional hook in case the layout wants to add changes to nameplates on event.

**Comment by Rainrider** [comment]
Haven't tested, just looked through the code. Any reason not to pass `"target"` as the third argument to the callback on PLAYER_TARGET_CHANGED?

**Comment by zorker** [comment]
Yes. The unit that stands for that nameplate is not "target" but sth like nameplates12 (could by any nameplate). One only needs access to nameplate.unitFrame which is given since we have access to the nameplate baseframe via C_NamePlate.

**Comment by zorker** [comment]
Can we replace this
```lua
local object
if nameplate then
  object = CreateFrame("Button", name, nameplate)
else
  object = CreateFrame("Button", name, oUF_PetBattleFrameHider, "SecureUnitButtonTemplate")
end
```
with that?
```lua
local object = nameplate and object = CreateFrame("Button", name, nameplate) or CreateFrame("Button", name, oUF_PetBattleFrameHider, "SecureUnitButtonTemplate")
```
If yes I would prefer the later.

**Comment by p3lim** [comment]
@zorker No, sacrificing readability for line numbers is not a good practice at all.

**Comment by zorker** [comment]
Does anyone know how far out 7.1 is?

Because I'm not sure if the following will affect the nameplate implementation:
http://us.battle.net/forums/en/wow/topic/20749494846

**Comment by zorker** [comment]
I tested the nameplates on the PTR. Everything working as intended.

But I have a really wierd bug on the PTR: http://eu.battle.net/forums/en/wow/topic/17613761364
The nameplateShowAll cvar has no effect. That has nothing to do with the change though. It affects the default UI aswell.

**Comment by zorker** [comment]
Screenshot from PTR
http://imgur.com/a/h3Dac

Found the solution to the friendly nameplate problem.
Blizzard added a new cvar that was set to 0 and there is currently no way to enable it other than setting it manually.
```
/run SetCVar("nameplateShowFriendlyNPCs",1)
```
All good. 👍

**Comment by zp** [comment]
I've noticed a small issue where the health statusbars sometimes don't update properly until you manually target the unit. (really only an issue with fairly large aoe pulls)

http://i.imgur.com/A7P0WeU.jpg (bottom right mob)

http://i.imgur.com/AJWrJZP.jpg (after manually targeting it)

**Comment by p3lim** [comment]
@zp Were you using `health.frequentUpdates = true`?

**Comment by zp** [comment]
I don't think I had it flagged, i'll try with it enabled.

**Comment by p3lim** [comment]
Afaik, nameplates don't work well with `UNIT_HEALTH`, they require `UNIT_HEALTH_FREQUENT`, which `health.frequentUpdates` enables.

**Comment by zorker** [comment]
Here is a full list of nameplate specific cvars. I would bet that the nameplateLargerScale cvar is for boss nameplates for example.

*Build 22731, WoW path 7.1, PTR*

```
nameplateClassResourceTopInset
nameplateGlobalScale
NamePlateHorizontalScale
nameplateLargeBottomInset
nameplateLargerScale
nameplateLargeTopInset
nameplateMaxAlpha
nameplateMaxAlphaDistance
nameplateMaxDistance
nameplateMaxScale
nameplateMaxScaleDistance
nameplateMinAlpha
nameplateMinAlphaDistance
nameplateMinScale
nameplateMinScaleDistance
nameplateMotion
nameplateMotionSpeed
nameplateOtherBottomInset
nameplateOtherTopInset
nameplateOverlapH
nameplateOverlapV
NameplatePersonalHideDelayAlpha
NameplatePersonalHideDelaySeconds
NameplatePersonalShowAlways
NameplatePersonalShowInCombat
NameplatePersonalShowWithTarget
nameplateSelectedAlpha
nameplateSelectedScale
nameplateSelfAlpha
nameplateSelfBottomInset
nameplateSelfScale
nameplateSelfTopInset
nameplateShowAll
nameplateShowEnemies
nameplateShowEnemyGuardians
nameplateShowEnemyMinions
nameplateShowEnemyMinus
nameplateShowEnemyPets
nameplateShowEnemyTotems
nameplateShowFriendlyGuardians
nameplateShowFriendlyMinions
nameplateShowFriendlyNPCs
nameplateShowFriendlyPets
nameplateShowFriendlyTotems
nameplateShowFriends
nameplateShowSelf
nameplateTargetBehindMaxDistance
NamePlateVerticalScale
ShowClassColorInNameplate
ShowNamePlateLoseAggroFlash
```

**Comment by p3lim** [comment]
@zorker Could you update that list of cvars with the defaults added?
We might want to set them for the user in the implementation.

**Comment by zorker** [comment]
@p3lim 
Will do.
Nameplate base frames shuffle units. We need to trigger nameplate.unitFrame:UpdateAllElements(event) OnEvent. I anchored it on the nameplate base frame because OnEvent we only get access to the nameplate base via C_NamePlate.GetNamePlateForUnit(unit). But that is all we need for the update.

**Comment by zorker** [comment]
Nameplates cvars with default values from PTR path 7.1.
https://github.com/zorker/rothui/blob/master/wow7.0/cvarlist/cvarlist.nameplate.only

oUF should not touch any of those. They are layout specific and only needed in very special cases.
The new nameplate spawn does not interfere with any of the nameplate cvars.

I just listed them because they where generated in the process of finding the bug on the PTR that was preventing friendly npc nameplates from spawning.

**Comment by p3lim** [comment]
> oUF should not touch any of those. They are layout specific and only needed in very special cases.

@zorker I was thinking we could allow setting those cvars through the "header" spawning, as they are relevant to the looks and functioning of the nameplates.
Basically have it work like the layout supplies attributes to SpawnHeader.

**Comment by zorker** [comment]
Sure you can do that. Nameplate cvars have to be set on PLAYER_LOGIN.
Not sure if we need to trigger the callback for the PLAYER_LOGIN event.

```lua
function oUF:SpawnNamePlates(styleName,namePrefix,nameplateCallback,nameplateCVars)
  ...
  function NPEH:PLAYER_LOGIN(event)
    if not nameplateCVars or type(nameplateCVars) ~= "table" then return end
    for key, value in next, nameplateCVars do
      SetCVar(key,value)
    end
  end
  NPEH:RegisterEvent("PLAYER_LOGIN")
end
```

**Comment by zorker** [comment]
Tested the implementation of the code above. Works well.

oUF/ouf.lua
https://github.com/zorker/rothui/blob/master/wow7.0/oUF_Simple/oUF/ouf.lua#L568

oUF_Simple/core/spawn.lua
https://github.com/zorker/rothui/blob/master/wow7.0/oUF_Simple/core/spawn.lua#L92

oUF_SimpleConfig/nameplate.lua
https://github.com/zorker/rothui/blob/master/wow7.0/oUF_SimpleConfig/nameplate.lua#L26

**Comment by gagou** [comment]
I tried it, it's working great.
Is it possible to make threat coloring working?

**Comment by zorker** [comment]
Threat coloring is handled by your layout. You can copy my example from oUF_Simple if you want.
Enabling threat coloring for the healthbar:
https://github.com/zorker/rothui/blob/master/wow7.0/oUF_Simple/core/functions.lua#L229
UpdateThreat forces an update on the healthbar
https://github.com/zorker/rothui/blob/master/wow7.0/oUF_Simple/core/functions.lua#L99
PostUpdate on healthbar triggers and adds threat color
https://github.com/zorker/rothui/blob/master/wow7.0/oUF_Simple/core/functions.lua#L88
Works perfectly on any unit.

**Comment by gagou** [comment]
I first tried using the threat element provided by oUF with an override on the Update function. It's working perfectly for any standard unit handled by my layout but not for nameplates.

I changed two things to make it work :
- I added a Threat:ForceUpdate() in my health post update.  I'm not sure that UNIT_THREAT_SITUATION_UPDATE fire for nameplate units, this way I'm sure that I'll update threat each time UNIT_HEALTH_FREQUENT fire.
- I changed my threat status in override from ````local status = UnitThreatSituation(unit)````
to
````
local status
if not UnitIsPlayer(unit) then
	status = UnitThreatSituation('player', unit)
elseif UnitIsFriend('player', unit) then
	status = UnitThreatSituation(unit)
end
````
This change allow me to know my threat situation against an enemy nameplate, and know threat situation for friendly player.

With those changes threat coloring is working for my nameplate layout.

**Comment by zorker** [comment]
I do the same. Tank bro? :)

**Comment by zorker** [comment]
You are right UNIT_THREAT_SITUATION_UPDATE does not fire very well at all.

**Comment by gagou** [comment]
I locally modified the Threat module to register UNIT_THREAT_LIST_UPDATE and removed the Threat:ForceUpdate() in my healt post update.
Threat is now updating correctly for my nameplates.

I think that Threat module should be modified to register UNIT_THREAT_LIST_UPDATE (by default or add an option in the layout to register it)

**Comment by p3lim** [comment]
Open up a separate issue or PR for that please.

**Comment by zorker** [comment]
Added the nameplateCVars functionality I was posting about before to the commit.

**Comment by Wetxius** [comment]
It's possible added Blizzard resource frame on player/target nameplate?
Or I should just use oUF class bars?

**Comment by zorker** [comment]
The Blizzard nameplate unitframes are disabled. You create them with oUF class icons or any class bar module. Remember that you only have one layout for all your nameplates. You need to hide/show specific frames if nameplates switch units. There is no way around that.

**Comment by Wetxius** [comment]
I found new error with Blizzard resourse frame. 

> ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:187: attempt to index field 'UnitFrame' (a nil value)
Count: 1
Call Stack:
[C]: ?
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:187: in function `SetupClassNameplateBar'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:211: in function `SetupClassNameplateBars'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:227: in function `SetClassNameplateBar'
...s\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:78: in function `ShowNameplateBar'
...s\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:67: in function `Setup'
...s\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:28: in function <...s\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:11>


If we enabled personal resource in options, on player or target, and playing monk/rogue select target (if show resouce on target), or entering in combat (show on player frame), and then changed our count of Chi (by talent in 3 row)/ changed combo points for Rogue (talents), then we have this error.
My solution: add in function oUF:SpawnNamePlates

> NamePlateDriverFrame.SetClassNameplateBar = function() end

Or maybe add

> NamePlateDriverFrame.SetupClassNameplateBars = function() end

**Comment by zorker** [comment]
We have a hook for UpdateNamePlateOptions.
```
NamePlateDriverFrame.UpdateNamePlateOptions = UpdateNamePlateOptions
```
That allows us to react on any changes the user made to the nameplate options.

It is possible that even with unregistering all the events there are functions left on the NamePlateDriverFrame that run into errors like the one posted above.

We can either manually disable functions that run into issues or unpack the NamePlateDriverFrame functions and disable all of them.

I will check the options later. Thanks for posting.

**Pull request closed without merging**
