### PR TITLE
core:  update the pet frame properly after entering/exiting a vehicle

### PR DESCRIPTION
**Pull request by Rainrider**
Fixes https://github.com/oUF-wow/oUF/issues/257
Closes https://github.com/oUF-wow/oUF/pull/258

It would be nice if someone manages to test this is a raid/party

### CODE REVIEW

**Comment by gagou** [comment]
I've done some test with my hunter in trial of the crusader and did not see any problem

**Comment by Rainrider** [comment]
@gagou we're you in a group? I mean I tested the player and pet frames myself. The interesting part is whether party/raid members are updated properly.

**Comment by ls-** [comment]
@gagou, we're talking about testing raid#, raid#pet, group#, group#pet frames now, cuz they might or might not be buggy 😕

**Comment by gagou** [comment]
I tested it in a party in trial of crusader with my hunt and mage (I have 3 wow accounts)
Group and grouppet frames are correctly updating when going in and out of vehicle, same for player and pet frame.
Raid frames are correctly updating, I tested them in Ulduar.
Can't test Raid pet I don't display pet for raid members in my layout.

**Comment by Rainrider** [comment]
@gagou Which layout did you use for testing? Or are you using headers for party/raid frames and the corresponding pets if you know that?

**Comment by gagou** [comment]
It's my own layout, I'm using header for party / raid

**Comment by Rainrider** [comment]
OK, thank you very much

**Pull request merged**
